import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./lib/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Robby&Bobby",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
        
      </body>
    </html>
  );
}
